# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-07 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_name', models.CharField(max_length=200)),
                ('security_symbol', models.CharField(max_length=200)),
                ('price_per_contract', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price_underlying', models.DecimalField(decimal_places=2, max_digits=7)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
