# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-09 19:38
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_post_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=tinymce.models.HTMLField(verbose_name='body'),
        ),
    ]
